### ISSUE TITLE
ERROR: Insufficient count of input/output paths supplied!         Expected 1 output paths and 2 input paths!         Got sys.argv: []

### ISSUE THREAD

**Issue by Kingxudong** [LiquidFun/Airway#15]
The defaults.yaml file path is set as follows
path: local
paths:
#    local: /home/anne/Anne/data/airway_vida_test/A2019RR46/

     local:  G:\Airway\A2069BH51\

The file structure is
![企业微信截图_1669025465841](https://user-images.githubusercontent.com/64447144/203023998-33c6578b-ff22-4f19-b6e9-d2a085e37004.png)
Error content prompts
ERROR: Insufficient count of input/output paths supplied!
        Expected 1 output paths and 2 input paths!
        Got sys.argv: []

**Comment by LiquidFun** [comment]
So do none of the stages work? 

And which command did you run? Can you post it exactly?

Also you have written the local variable 2 times in your post. Which is it? And are you on Windows or Linux?
```yaml
path: local
paths:
   - local: /home/anne/Anne/data/airway_vida_test/A2019RR46/   # <- this one?
   - local: G:\Airway\A2069BH51\     # or this one?
```
